[project]
name = "iot-rpc-rest-app"
version = "0.1.0"
description = "Iot Async-RPC Core app"
requires-python = ">=3.13"
dependencies = [
    "aio-pika>=9.5.7",
    "alembic>=1.16.4",
    "apscheduler[sqlalchemy]>=3.11.0",
    "asyncpg>=0.30.0",
    "black>=25.1.0",
    "fastapi>=0.118.0",
    "fastapi-pagination>=0.14.1",
    "faststream>=0.5.48",
    "fastui>=0.8.0",
    "gunicorn>=23.0.0",
    "httpx>=0.28.1",
    "orjson>=3.11.3",
    "pydantic>=2.11.9",
    "pydantic-settings>=2.10.1",
    "sqlalchemy>=2.0.43",
    "uvicorn>=0.37.0",
]
